### ISSUE TITLE
Matrix symbols corraptes sometimes

### ISSUE THREAD

**Issue by mvchn** [metacortex-software/metacortex-frontend#2]
In the Chrome browser, some symbols on the matrix are coded by "?" symbol

**Comment by ACraft4** [comment]
The problem is not solved. I tried to fix it by connecting fonts, but it didn't work.

**Comment by mvchn** [comment]
@ACraft4 try to review the pull request https://github.com/metacortex-software/metacortex-frontend/pull/4
